### ISSUE TITLE
MavensMate post 5.0 update sits compiling for 5+ minutes on every save

### ISSUE THREAD

**Issue by Brugge** [joeferraro/MavensMate-SublimeText#686]
I am unsure what is going on here.  Ever since the 5.0 update, the stability of MavensMate seems to be completely degrading.  Every time I save a file, it sits at "Operation: Compiling" for 5+ minutes on average with the result indicator bouncing back and forth.  Saving used to take seconds.  Is there something I am doing wrong here?

**Comment by chris-4211** [comment]
Hi,
I'm experiencing a similar thing. It's not 5 minutes but varies between 30sec (fast) and 2 minutes.
The delay is reproducible on different machines from different internet connections.
Unfortunately Git's "Attach" function does not seem to work, so I'll just c&p my logs here...

Let me know if you need anything else - I'd be glad to help.
Btw. great job you're doing here - everyone around here loves MM!

Cheers
Chris

```
2015-10-02T05:31:04.715Z - info: initiated client:  {"name":"mavensmate-app","isServer":true,"isNodeApp":false,"isCommandLine":false,"settings":{"type":"literal"}}
2015-10-02T05:31:23.621Z - info: adding project by id ---->  SB69W4TGZ33JV8VSPLXL15XH0X19R4P5
2015-10-02T05:31:23.622Z - info: path:  C:\Users\chris\workspace\MavensMate\Customer - Sandbox
2015-10-02T05:31:27.039Z - info: 

==================> executing command: compile-metadata

2015-10-02T05:31:27.039Z - info: executeCommandForProject payload is: {"paths":["C:\\Users\\chris\\workspace\\MavensMate\\Customer - Sandbox\\src\\classes\\FormUtils.cls"]}
2015-10-02T05:32:41.960Z - info: Looking for finish command(s) for compile-metadata
2015-10-02T05:32:41.961Z - info: 

==================> executing command: index-apex-class

2015-10-02T05:32:41.961Z - info: executeCommandForProject payload is: {"className":"C:\\Users\\chris\\workspace\\MavensMate\\Customer - Sandbox\\src\\classes\\FormUtils.cls"}
2015-10-02T05:32:41.965Z - info: Running finish commands for command: compile-metadata _bitField=0, _fulfillmentHandler0=undefined, _rejectionHandler0=undefined, _progressHandler0=undefined, _promise0=undefined, _receiver0=undefined, _settledValue=undefined, _boundTo=undefined
2015-10-02T05:32:41.967Z - info: handling command result: 
2015-10-02T05:32:42.786Z - info: Looking for finish command(s) for index-apex-class
2015-10-02T05:32:42.787Z - info: handling command result: 
2015-10-02T05:32:42.787Z - info: Finish commands successfully run for command: compile-metadata paths=[C:\Users\chris\workspace\MavensMate\Customer - Sandbox\src\classes\FormUtils.cls]
```

**Comment by Avarga954** [comment]
also experiencing this and so is my whole team

**Comment by ThyRavenXIII** [comment]
I am having the same issue, making Development extremely slow, will have to go over to the Dev Console instead until this is fixed, can't work with it as it is.

**Comment by joeferraro** [comment]
hey guys, really sorry to hear that compilation is so slow. Would you mind helping me by specifying things like:

1. your platform
2. version of mm-app
3. whether this happens with EVERY project or just some
4. whether you're behind a proxy
5. whether this persists with conflict checking turned OFF in mm-app's settings

thanks very much

**Comment by ThyRavenXIII** [comment]
1. Windows 10
2. V0.0.8
3. Seems to be every project
4. I'm behind a company firewall but i've never had a problem before, only after the 5 update
5.I have tried with conflict checking on and off, doesn't seem to effect it.

**Comment by chris-4211** [comment]
Hi,

Thanks for your reply.

- Windows 10
- 0.0.8 (also happened in the last version, 0.0.7 I think)
- so far every project (tried 3 so far)
- not behind any firewall or proxy
- persists without conflict checks (my log shows results with conflict checks turned off)

----- Ursprüngliche Nachricht -----
Von: "Joe Ferraro" <notifications@github.com>
Gesendet: ‎02.‎10.‎2015 12:44
An: "joeferraro/MavensMate-SublimeText" <MavensMate-SublimeText@noreply.github.com>
Cc: "chris-4211" <christoph.eschweiler+git@gmail.com>
Betreff: Re: [MavensMate-SublimeText] MavensMate post 5.0 update sitscompiling for 5+ minutes on every save (#686)

hey guys, really sorry to hear that compilation is so slow. Would you mind helping me by specifying things like:
your platform 
version of mm-app 
whether this happens with EVERY project or just some 
whether you're behind a proxy 
whether this persists with conflict checking turned OFF in mm-app's settings 
thanks very much

**Comment by Brugge** [comment]
1. Windows 10 (Others on WIndows 8/8.1 having this issue as well)
2. 0.0.8 (has happened on all versions of the app though)
3. Always
4. No
5. I tried toggling the tooling api option but not the conflict checking yet, will try that.
6. Different versions, happening on Winter '16 orgs and Summer '15 orgs
7. Refreshes seem slightly faster, but everything is WAY slower to process than it was before.

**Comment by Brugge** [comment]
It appears as though from the Salesforce end the files are being saved pretty quickly, but something is happening where on the sublimeText/MavensMate end the result indicator is just bouncing back and forth for minutes, not sure if that helps at all.

**Comment by joeferraro** [comment]
Any info is helpful, thanks @Brugge. Curious, what kind of specs are on your machine, RAM/CPU?

**Comment by Brugge** [comment]
Core i7-4600U @ 2.1 GHz 2.70 GHz
16GB RAM

**Comment by joeferraro** [comment]
Ha, so there should be NO problem. OK, will continue to dig in. I've been running on Windows 10 without issue all day today, hitting a development environment. Will focus in on this piece of feedback:

> It appears as though from the Salesforce end the files are being saved pretty quickly, but something is happening where on the sublimeText/MavensMate end the result indicator is just bouncing back and forth for minutes, not sure if that helps at all.

**Comment by TracerBullet21** [comment]
I am having the same issue as above. I am averaging about 4 minutes per save, even when saving JS resources. 

1. 64 Bit Windows 8
2. Version 5.0.4
3. So far, every project
4. I am not behind a proxy. 
5. I have not tried with that setting off. 

It seems like the file is actually being saved on the server but MavensMate does not know this. When I save, I will occasionally get a timeout error but the file in SF was actually updated.

I love Maven's Mate btw. Please don't make me go back to Eclipse even for a little while :(

**Comment by groundwired** [comment]
Same here.  2-10 mins per save.  I have NOT upgraded to v5 however.

1. OS X Yosemite
2. MM version 4.0.5
3. My org is on Winter 16.

**Comment by joeferraro** [comment]
@groundwired thanks very much for this information as it's helping us to understand whether this is truly an issue on our side. I have a suspicion this is an issue with the metadata api, which is, unfortunately, not surprising.

**Comment by joeferraro** [comment]
for folks having issues with compile times, you may want to install the latest mm-app beta, as i've introduced a streamline compilation method that circumvents the metadata api when compiling apex & vf metadata: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.9-beta4

please update this thread with your experiences.

**Comment by chris-4211** [comment]
Hi,

I've tried with the new version (0.0.9) and is significantly faster - now takes about 20sec.
I've created a new log if you need one...

```
==================> executing command: compile-metadata

2015-10-05T08:27:20.314Z - info: executeCommandForProject payload is: {"paths":["C:\\Users\\chris\\workspace\\MavensMate\\Customer - Sandbox\\src\\classes\\FormUtils.cls"]}
2015-10-05T08:27:20.314Z - debug: command class is: CompileMetadataCommand
2015-10-05T08:27:20.315Z - debug: compiling paths: 
2015-10-05T08:27:20.315Z - debug:  0=C:\Users\chris\workspace\MavensMate\Customer - Sandbox\src\classes\FormUtils.cls
2015-10-05T08:27:20.316Z - debug: compiling via tooling api
2015-10-05T08:27:20.322Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:20.322Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:20.827Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:20.827Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:20.957Z - debug: new container id is: 1dcc0000000F8k2AAC
2015-10-05T08:27:20.958Z - debug: Creating tooling member:
2015-10-05T08:27:20.959Z - silly: public with sharing class FormUtils
{
	// --- SNIP --- Class content
}
2015-10-05T08:27:20.959Z - debug: 1dcc0000000F8k2AAC
2015-10-05T08:27:20.962Z - debug: 01pc0000000LwGJAA0
2015-10-05T08:27:21.334Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:21.335Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:21.841Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:21.842Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:22.348Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:22.348Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:22.855Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:22.855Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:22.984Z - debug: _pollAsyncContainer for requestId: 1drc0000001JNeGAAW
2015-10-05T08:27:23.359Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:23.359Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:23.861Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:23.861Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:24.364Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:24.364Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:24.867Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:24.867Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:25.369Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:25.369Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:25.872Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:25.872Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:26.374Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:26.375Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:26.877Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:26.877Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:27.380Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:27.380Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:27.883Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:27.883Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:28.389Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:28.389Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:28.896Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:28.897Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:29.404Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:29.404Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:29.912Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:29.912Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:30.419Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:30.420Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:30.928Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:30.928Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:31.436Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:31.436Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:31.942Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:31.943Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:32.450Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:32.451Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:32.958Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:32.959Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:33.464Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:33.464Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:33.970Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:33.970Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:34.477Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:34.477Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:34.984Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:34.984Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:35.490Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:35.490Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:35.998Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:35.998Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:36.504Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:36.505Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:37.010Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:37.011Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:37.517Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:37.519Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:37.765Z - debug: asyncContainerRequestCompleteHandler
2015-10-05T08:27:37.766Z - debug: deleting container id:
2015-10-05T08:27:37.766Z - debug: 1dcc0000000F8k2AAC
2015-10-05T08:27:37.766Z - silly:  type=ContainerAsyncRequest, url=/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001JNeGAAW, Id=1drc0000001JNeGAAW, MetadataContainerId=1dcc0000000F8k2AAC, MetadataContainerMemberId=null, State=Completed, IsCheckOnly=false, allComponentMessages=[], componentFailures=[], componentSuccesses=[], runTestResult=null, ErrorMsg=null
2015-10-05T08:27:38.027Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:38.027Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:38.483Z - debug: compile via tooling api result: 
2015-10-05T08:27:38.483Z - debug:  type=ContainerAsyncRequest, url=/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001JNeGAAW, Id=1drc0000001JNeGAAW, MetadataContainerId=1dcc0000000F8k2AAC, MetadataContainerMemberId=null, State=Completed, IsCheckOnly=false, allComponentMessages=[], componentFailures=[], componentSuccesses=[], runTestResult=null, ErrorMsg=null
2015-10-05T08:27:38.484Z - debug: getting server properties ...
2015-10-05T08:27:38.484Z - silly:  path=C:\Users\chris\workspace\MavensMate\Customer - Sandbox\src\classes\FormUtils.cls, _path=C:\Users\chris\workspace\MavensMate\Customer - Sandbox, accessToken=XXX, instanceUrl=https://cs14.salesforce.com, username=XXX, password=XXX, orgType=sandbox, loginUrl=, apiVersion=34.0, sfdcclient-cache-refresh=function () {
              logger.debug('project caught event: sfdcclient-cache-refresh');
              self._writeSession()
                .then(self._getCachedSession())
                .catch(function(err) {
                  logger.debug('sfdcclient-cache-refresh: could not update local session cache');
                  throw new Error('Could not update local session cache: '+err.message);
                })
                .done();
  -- SNIP --
2015-10-05T08:27:38.532Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:38.532Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:39.036Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:39.036Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:39.143Z - silly:  type=ApexClass, url=/services/data/v34.0/sobjects/ApexClass/01pc0000000LwGJAA0, Id=01pc0000000LwGJAA0, Name=FormUtils, CreatedDate=2015-09-08T12:20:36.000+0000, CreatedById=005D0000003kLuuIAE, NamespacePrefix=null, type=User, url=/services/data/v34.0/sobjects/User/005D0000003kLuuIAE, Name=chris, LastModifiedById=005D0000003kLuuIAE, LastModifiedDate=2015-10-05T08:27:36.000+0000, type=User, url=/services/data/v34.0/sobjects/User/005D0000003kLuuIAE, Name=chris
2015-10-05T08:27:39.164Z - silly: getting metadata type by name: ApexClass
2015-10-05T08:27:39.164Z - silly:  directoryName=classes, inFolder=false, metaFile=true, suffix=cls, xmlName=ApexClass
2015-10-05T08:27:39.164Z - debug:  directoryName=classes, inFolder=false, metaFile=true, suffix=cls, xmlName=ApexClass
2015-10-05T08:27:39.177Z - debug: flattening results: 
2015-10-05T08:27:39.177Z - debug: compile result:
2015-10-05T08:27:39.177Z - debug:  type=ContainerAsyncRequest, url=/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001JNeGAAW, Id=1drc0000001JNeGAAW, MetadataContainerId=1dcc0000000F8k2AAC, MetadataContainerMemberId=null, State=Completed, IsCheckOnly=false, allComponentMessages=[], componentFailures=[], componentSuccesses=[], runTestResult=null, ErrorMsg=null
2015-10-05T08:27:39.178Z - debug: compile results: 
2015-10-05T08:27:39.178Z - debug: {"checkOnly":false,"completedDate":"","createdBy":"","createdByName":"","createdDate":"","details":{"componentSuccesses":[{"attributes":{"type":"ContainerAsyncRequest","url":"/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001JNeGAAW"},"Id":"1drc0000001JNeGAAW","MetadataContainerId":"1dcc0000000F8k2AAC","MetadataContainerMemberId":null,"State":"Completed","IsCheckOnly":false,"DeployDetails":{"allComponentMessages":[],"componentFailures":[],"componentSuccesses":[],"runTestResult":null},"ErrorMsg":null}],"runTestResult":{"numFailures":"0","numTestsRun":"0","totalTime":"0.0"},"componentFailures":[]},"done":false,"id":"","ignoreWarnings":false,"lastModifiedDate":"","numberComponentErrors":0,"numberComponentsDeployed":1,"numberComponentsTotal":0,"numberTestErrors":0,"numberTestsCompleted":0,"numberTestsTotal":0,"rollbackOnError":false,"runTestsEnabled":"false","startDate":"","status":"","success":true}
2015-10-05T08:27:39.179Z - info: Looking for finish command(s) for compile-metadata
2015-10-05T08:27:39.179Z - info: 

==================> executing command: index-apex-class

2015-10-05T08:27:39.179Z - info: executeCommandForProject payload is: {"className":"C:\\Users\\chris\\workspace\\MavensMate\\Customer - Sandbox\\src\\classes\\FormUtils.cls"}
2015-10-05T08:27:39.179Z - debug: command class is: IndexApexClassCommand
2015-10-05T08:27:39.180Z - debug: _getSymbolsForClassNames:
2015-10-05T08:27:39.180Z - debug:  0=FormUtils
2015-10-05T08:27:39.181Z - info: Running finish commands for command: compile-metadata _bitField=0, _fulfillmentHandler0=undefined, _rejectionHandler0=undefined, _progressHandler0=undefined, _promise0=undefined, _receiver0=undefined, _settledValue=undefined, _boundTo=undefined
2015-10-05T08:27:39.181Z - info: handling command result: 
2015-10-05T08:27:39.182Z - debug:  checkOnly=false, completedDate=, createdBy=, createdByName=, createdDate=, componentSuccesses=[type=ContainerAsyncRequest, url=/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001JNeGAAW, Id=1drc0000001JNeGAAW, MetadataContainerId=1dcc0000000F8k2AAC, MetadataContainerMemberId=null, State=Completed, IsCheckOnly=false, allComponentMessages=[], componentFailures=[], componentSuccesses=[], runTestResult=null, ErrorMsg=null], numFailures=0, numTestsRun=0, totalTime=0.0, componentFailures=[], done=false, id=, ignoreWarnings=false, lastModifiedDate=, numberComponentErrors=0, numberComponentsDeployed=1, numberComponentsTotal=0, numberTestErrors=0, numberTestsCompleted=0, numberTestsTotal=0, rollbackOnError=false, runTestsEnabled=false, startDate=, status=, success=true
2015-10-05T08:27:39.182Z - debug: finishing jobid: e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:39.182Z - silly:  checkOnly=false, completedDate=, createdBy=, createdByName=, createdDate=, componentSuccesses=[type=ContainerAsyncRequest, url=/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001JNeGAAW, Id=1drc0000001JNeGAAW, MetadataContainerId=1dcc0000000F8k2AAC, MetadataContainerMemberId=null, State=Completed, IsCheckOnly=false, allComponentMessages=[], componentFailures=[], componentSuccesses=[], runTestResult=null, ErrorMsg=null], numFailures=0, numTestsRun=0, totalTime=0.0, componentFailures=[], done=false, id=, ignoreWarnings=false, lastModifiedDate=, numberComponentErrors=0, numberComponentsDeployed=1, numberComponentsTotal=0, numberTestErrors=0, numberTestsCompleted=0, numberTestsTotal=0, rollbackOnError=false, runTestsEnabled=false, startDate=, status=, success=true
2015-10-05T08:27:39.542Z - debug: Processing request GET for URL: /status?id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:39.543Z - debug: query params id=e5402690-6b3a-11e5-9ec7-3b782b6129f4
2015-10-05T08:27:40.258Z - debug: done indexing symbols!
2015-10-05T08:27:40.259Z - info: Looking for finish command(s) for index-apex-class
2015-10-05T08:27:40.259Z - info: handling command result: 
2015-10-05T08:27:40.259Z - debug: Symbols successfully indexed for C:\Users\chris\workspace\MavensMate\Customer - Sandbox\src\classes\FormUtils.cls
2015-10-05T08:27:40.259Z - info: Finish commands successfully run for command: compile-metadata paths=[C:\Users\chris\workspace\MavensMate\Customer - Sandbox\src\classes\FormUtils.cls]
```

**Comment by Avarga954** [comment]
@joeferraro  This issue seems to have corrected itself for my team on cs7. We have not made any configuration changes since i last posted. i am using 4.5 and my teammate is using 5.0 and all issues with save times seemed to have been resolved today. I believe this is was a server side issue

**Comment by ThyRavenXIII** [comment]
Still no difference for myself, still long wait times to compile, using V0.0.9 Beta 4 with Sublime 3

**Comment by sp0ken** [comment]
I have the same issue and it also generates an usually high number of api requests (around 200 per save try, I hit the 15 000 limit once). Although this issue is intermittent and pop ups once a week.
1. Linux Mint 17.3 x64
2. MavenMate for Sublime v6
