### ISSUE TITLE
Can not Run test method

### ISSUE THREAD

**Issue by jairzh** [joeferraro/MavensMate-SublimeText#766]
I got the following error after click Run Tests button:

`Server raised fault: 'INVALID_OPERATION: runTests can only be used with a testLevel of RunSpecifiedTests'`

**Comment by mandyrawat** [comment]
I am getting same error when I am trying to run the test case through 'Test runner UI' but it works fine when as run it through 'Run Async Apex Tests For This Class'.

**Comment by daeschwed** [comment]
Hi all

This issue seems to have been resolved a while back.
Running tests no longer causes this error. Seems to be related to a couple salesforce releases back when they made some changes to the deployment process, as in you could choose what tests to run.

Can confirm that this now works just as expected, at least on OS X.
OS X El Capitan v10.11.4
Sublime Text 3 Build 3103
MavensMate for Sublime Text v7.0.0-beta.1
MavensMate-app v0.0.11-beta1

Please test again. If it still fails, please post versions in use, as above.
Just a guess - you're not using the prerelease build. However you'll probably want to… #769 

Cheers
the swedish guy

**Comment by DougThompson** [comment]
This seems to still be an error.  I am using v6 and API level 36 and I still get this error when trying to run tests.  Change back to API level 33, and everything works just fine.
